apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw-verifiers-vllm-server-grpo
  labels:
    app: verifiers-vllm
    task: serving # Task label for anti-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verifiers-vllm
  template:
    metadata:
      labels:
        app: verifiers-vllm # Pods get this label
        task: serving     # And this task label
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 500Gi # Adjust size as needed
      - name: config-volume
        configMap:
          name: cw-verifiers-train-grpo-config
      - name: model-checkpoints
        persistentVolumeClaim:
          claimName: model-checkpoints
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: task # Avoid pods with these task labels
                operator: In
                values:
                - training
                - rewards
            topologyKey: "kubernetes.io/hostname" # Spread across different nodes
      # Uncomment and configure if your image is in a private registry:
      # imagePullSecrets:
      # - name: my-registry-secret
      containers:
      - name: verifiers-vllm-container
        image: ghcr.io/tcapelle/triton_eval:1906 # <-- UPDATE THIS
        workingDir: /app/
        command: ["sh"]
        args:
          - "-c"
          - |
            # Pull latest verifiers_dev if requested
            if [ "${PULL_LATEST:-false}" = "true" ]; then
              echo "🔄 Pulling latest verifiers_dev code..."
              cd /app/verifiers_dev && git pull origin main
              echo "✅ Code updated successfully"
            fi
            
            # trl
            pip install git+https://github.com/tcapelle/verifiers.git@weave

            # Run vllm server
            vf-vllm --config /mnt/verifiers-config/config.yaml
        resources:
          limits:
            nvidia.com/gpu: "8"
            cpu: "64"
            memory: "1500Gi"
          requests:
            cpu: "32"
            memory: "1000Gi"
            nvidia.com/gpu: "8"
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: config-volume
          mountPath: /mnt/verifiers-config
        - mountPath: /model-checkpoints
          name: model-checkpoints
        # If vllm-serve listens on a port (e.g., 8000) and you need to expose it:
        ports:
        - containerPort: 8000
          name: http-vllm
        - containerPort: 51216
          name: weight-updates
      # Add tolerations if your GPU nodes have taints
      # tolerations:
      # - key: "nvidia.com/gpu"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # Add nodeSelector if you need to target specific types of GPU nodes
      # nodeSelector:
      #   cloud.google.com/gke-accelerator: nvidia-tesla-t4 # Example for GKE 
---
apiVersion: v1
kind: Service
metadata:
  name: cw-verifiers-vllm-service
spec:
  selector:
    app: verifiers-vllm # Matches the labels of the pods in your Deployment
  ports:
    - protocol: TCP
      port: 8000 # Port on which the service is exposed
      targetPort: 8000 # Port on the pod to forward traffic to (containerPort)
      name: http-vllm
    - protocol: TCP
      port: 51216
      targetPort: 51216
      name: weight-updates
  type: ClusterIP 